export const actionsData = [
  {
    n: 5,
    responsavel: "CG/Navega",
    linhaAcao: "Conservação",
    unidade: "UP1",
    trecho: "1.1. ; 1.2.",
    acao: "Buscar a criação de Grupo de moradores da área do manguezal (RPPN)",
    finalidade: "Acessar fundo do meio ambiente para destinar ao rio Gravatá; fomentar a criação de UC",
    parceiros: "Município",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Criação do grupo informal de moradores para discussão sobre RPPNs",
    resultados2025: "0 - apoiar a organização da associação - executar oficinas de sensibilização para a preservação",
    status: "Mudança de estratégia - previsto",
    comprovação: "-",
    observacoes: "Atualmente existem processos de regularização de moradias - formalizar/mobilizar aos moradores a criação de um grupo e suas RPPNs (oficina) - chamar para reunião CG/Navega"
  },
  {
    n: 13,
    responsavel: "CG/Navega",
    linhaAcao: "Conservação",
    unidade: "UP1",
    trecho: "1.1. ; 1.2.",
    acao: "Estudar dispositivo de criação de unidades de conservação",
    finalidade: "Proteção das áreas",
    parceiros: "Município",
    prazo: "Longo",
    duracao: "Contínua",
    indicadores: "Número de reuniões do grupo sobre RPPN; Lançamento de projeto de criação de Unidade de Conservação",
    resultados2025: "0 - apoiar a organização da associação - executar oficinas de sensibilização sobre RPPN",
    status: "Mudança de estratégia - previsto",
    comprovação: "-",
    observacoes: "Processos de regularização de moradias - formalizar/mobilizar aos moradores a criação de um grupo e suas RPPNs (oficina) - chamar para reunião CG/Navega"
  },
  {
    n: 91,
    responsavel: "Fundação Cultural",
    linhaAcao: "Cultura",
    unidade: "UP2",
    trecho: "2.2. ; 2.3. ; 2.4.",
    acao: "Verificar com artesãos locais e terceirizada da limpeza da praia a viabilidade e intenção de criação de artesanato com resíduos da praia - levar a ideia para a Cultura para a criação de um Plano de Negócios",
    finalidade: "Geração de renda",
    parceiros: "Instituições de ensino e pesquisa, OSC",
    prazo: "Médio",
    duracao: "Pontual - Contínua",
    indicadores: "Lançamento do Plano de negócios local - reutilização dos resíduos da praia",
    resultados2025: "O artesanato continua, sem plano de negócios. Sob análise com a pasta da Cultura.",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 109,
    responsavel: "Fundação Cultural",
    linhaAcao: "Cultura",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Elaborar projeto de criação de museu histórico da cultura da pesca",
    finalidade: "Fomentar o uso turístico do local, preservar a cultura do pescador artesanal, valorização da gastronomia local e recursos do mar",
    parceiros: "Instituições privadas; OSC, SPU; sistema S",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Local para o museu; Lançamento do projeto do museu da pesca de Navegantes",
    resultados2025: "Sob análise com a pasta da Cultura.",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 97,
    responsavel: "Gabinete do Prefeito",
    linhaAcao: "Cultura",
    unidade: "UP3",
    trecho: "3.1.",
    acao: "Desapropriação e recuperação da área caso seja cabível a desocupação",
    finalidade: "Continuidade de usos da área",
    parceiros: "Autoridade portuária; SPU",
    prazo: "Longo",
    duracao: "Contínua",
    indicadores: "Número de acordos e de desocupações executadas; área recuperada (m²)",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 2,
    responsavel: "Instituto Ambiental de Navegantes - IAN",
    linhaAcao: "Educação Ambiental",
    unidade: "UP1",
    trecho: "1.2.",
    acao: "Apoiar ações com entidades públicas e privadas para execução de educação ambiental e preservação do ambiente",
    finalidade: "Melhoria da qualidade de vida dos moradores e preservação da fauna e flora",
    parceiros: "GTEAN; associação de moradores e Prefeitura de Navegantes",
    prazo: "Longo",
    duracao: "Sazonal",
    indicadores: "Número de projetos de educação ambiental e preservação implementados no trecho",
    resultados2025: "Sem ações diretas na UP1. Ações indiretas - projeto nas escolas Oceano sem Plástico",
    status: "Previsto. Em execução ações indiretas",
    comprovação: "Anexo 01",
    observacoes: "Buscar a realização de ações do Limpando o Mundo e Juntos pelo Rio, e outras ações de educação ambiental (ex. escolas), na UP1"
  },
  {
    n: 12,
    responsavel: "Instituto Ambiental de Navegantes - IAN",
    linhaAcao: "Conservação",
    unidade: "UP1",
    trecho: "1.1.",
    acao: "Estudar a boa prática de São Bento do Sul - fundo para a preservação do manguezal",
    finalidade: "Angariar recursos para poder realizar ações de preservação do Manguezal",
    parceiros: "OSC",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Lançamento de estudo do fundo de proteção ao Manguezal",
    resultados2025: "Necessidade de outras ações anteriores - Criação de um GT Rio Gravatá no CG/Navega",
    status: "Mudança de estratégia - Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 19,
    responsavel: "Instituto Ambiental de Navegantes - IAN",
    linhaAcao: "Educação Ambiental",
    unidade: "UP1",
    trecho: "1.1. ; 1.2.",
    acao: "Implementar / fomentar projetos de interpretação e sinalização ambiental",
    finalidade: "Tornar o local apropriado ao ecoturismo e segurança; infraestrutura adequada",
    parceiros: "OSC; Instituições privadas; UC",
    prazo: "Longo",
    duracao: "Sazonal",
    indicadores: "Número de painéis de interpretação paisagem instalados no trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "IAN via Fundo do Meio Ambiente",
    observacoes: ""
  },
  {
    n: 23,
    responsavel: "Instituto Ambiental de Navegantes - IAN",
    linhaAcao: "Conservação",
    unidade: "UP2",
    trecho: "2.2. ; 2.3. ; 2.4.",
    acao: "Acelerar atividades de erradicação de exóticas na restinga",
    finalidade: "Implementar ações previstas no TAC; facilitar o desenvolvimento da vegetação nativa",
    parceiros: "OSC",
    prazo: "Longo",
    duracao: "Contínua",
    indicadores: "Volume ou área de exóticas removidas do trecho",
    resultados2025: "PRAD em execução - detalhes sob análise junto à pasta",
    status: "Em execução - contínua",
    comprovação: "Anexo 03 e 04",
    observacoes: "Existem Projetos de Recuperação da Restinga da orla municipal, setorizados em dois trechos: o trecho norte está em fase de execução de ações (executado pela Portonave - Acquaplan), abrange parcialmente os trechos 2.2, 2.3. e 2.4., e foi apresentado em reunião do Comitê Gestor; e o trecho sul em elaboração de projeto (executado pela Arteris? - Seiba). Com a alimentação da Praia do Gravatá, também é prevista a recuperação da restinga do trecho 2.1., visando dar maior durabilidade à obra."
  },
  {
    n: 29,
    responsavel: "Instituto Ambiental de Navegantes - IAN",
    linhaAcao: "Conservação",
    unidade: "UP2",
    trecho: "2.2. ; 2.3. ; 2.4.",
    acao: "Avaliar a viabilidade de criação de Unidade de Conservação no cordão de dunas frontais",
    finalidade: "Verificar a pertinência e atender ao PGI anterior, buscando uma solução integrada para a proteção e uso sustentável da restinga recuperada da orla de Navegantes. Instalação de guaritas, passarelas e Centros de Interpretação Ambiental.",
    parceiros: "Instituições de ensino e pesquisa, OSC",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Resultado do estudo de viabilidade de UC",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 51,
    responsavel: "Instituto Ambiental de Navegantes - IAN",
    linhaAcao: "Conservação",
    unidade: "UP2",
    trecho: "2.1.",
    acao: "Elaborar estudo para identificação de viabilidade para a criação de uma unidade de conservação na Ilhota",
    finalidade: "Criar dispositivo de proteção da nidificação",
    parceiros: "Iniciativa privada, instituições de ensino e pesquisa, OSC",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Contratação de estudo para a criação de UC - Lançamento do estudo para a criação de UC na Ilhota",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: "Verificar realidade após engordamento da praia - conexão ilhota - previsto no projeto"
  },
  {
    n: 53,
    responsavel: "Instituto Ambiental de Navegantes - IAN",
    linhaAcao: "Conservação",
    unidade: "UP2",
    trecho: "2.2. ; 2.3. ; 2.4.",
    acao: "Elaborar um estudo e plano de manejo das areias que escapam para o deck e acessos à praia",
    finalidade: "Otimizar a manutenção que atualmente é manual - inviável; Incluir proposta de manejo ao TAC",
    parceiros: "SPU, MPF",
    prazo: "Médio",
    duracao: "Pontual - implementação contínua",
    indicadores: "Lançamento do estudo do escape de manejo de areias da orla",
    resultados2025: "PRAD em execução - detalhes sob análise junto à pasta",
    status: "Em execução",
    comprovação: "Anexo 03 e 04",
    observacoes: "Existem Projetos de Recuperação da Restinga da orla municipal, setorizados em dois trechos: o trecho norte está em fase de execução de ações (executado pela Portonave - Acquaplan), abrange parcialmente os trechos 2.2, 2.3. e 2.4., e foi apresentado em reunião do Comitê Gestor, contemplando medidas de contenção de escape de areia; e o trecho sul em elaboração de projeto (executado pela Arteris? - Seiba). Com a alimentação da Praia do Gravatá, também é prevista a recuperação da restinga do trecho 2.1., visando dar maior durabilidade à obra."
  },
  {
    n: 71,
    responsavel: "Instituto Ambiental de Navegantes - IAN",
    linhaAcao: "Educação Ambiental",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Fomentar iniciativas de interpretação ambiental - ex. Roteiro Geoecológico",
    finalidade: "Divulgar a natureza local e reduzir a degradação",
    parceiros: "Iniciativa privada, instituições de ensino e pesquisa, OSC",
    prazo: "Curto",
    duracao: "Contínua",
    indicadores: "Número de painéis de interpretação paisagem instalados no trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "IAN via Fundo do Meio Ambiente",
    observacoes: ""
  },
  {
    n: 76,
    responsavel: "Instituto Ambiental de Navegantes - IAN",
    linhaAcao: "Educação Ambiental",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Implementar o projeto Guardiões da Praia / monitoramento",
    finalidade: "Proporcionar mais segurança na orla",
    parceiros: "Iniciativa privada, instituições de ensino e pesquisa, OSC",
    prazo: "Médio",
    duracao: "Contínua",
    indicadores: "Número de ações do projeto Guardiões da praia efetuadas no trecho",
    resultados2025: "0",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 83,
    responsavel: "Instituto Ambiental de Navegantes - IAN",
    linhaAcao: "Conservação",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Manter e fortalecer o Programa de recuperação da restinga",
    finalidade: "Identificar e recuperar trechos vulneráveis à erosão",
    parceiros: "Instituições de ensino e pesquisa, OSC",
    prazo: "Longo",
    duracao: "Contínua",
    indicadores: "Área de restinga recuperada no trecho / Ações de manejo para a recuperação do trecho",
    resultados2025: "PRAD em execução - detalhes sob análise junto à pasta",
    status: "Em execução - contínua",
    comprovação: "Anexo 03 e 04",
    observacoes: "Existem Projetos de Recuperação da Restinga da orla municipal, setorizados em dois trechos: o trecho norte está em fase de execução de ações (executado pela Portonave - Acquaplan), abrange parcialmente os trechos 2.2, 2.3. e 2.4., e foi apresentado em reunião do Comitê Gestor; e o trecho sul em elaboração de projeto (executado pela Arteris? - Seiba). Com a alimentação da Praia do Gravatá, também é prevista a recuperação da restinga do trecho 2.1., visando dar maior durabilidade à obra."
  },
  {
    n: 11,
    responsavel: "IAN e SEPLAN",
    linhaAcao: "Turismo",
    unidade: "UP1",
    trecho: "1.2.",
    acao: "Elaborar projeto de Deck para contemplação do Manguezal",
    finalidade: "Dar acesso à população para observar o Manguezal",
    parceiros: "Município; OSC e instituições privadas",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Ter projeto aprovado",
    resultados2025: "Necessidade de outras ações anteriores - Criação de um GT Rio Gravatá no CG/Navega",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 25,
    responsavel: "IAN e SEAP",
    linhaAcao: "Fiscalização",
    unidade: "UP2",
    trecho: "2.1.",
    acao: "Aumentar a fiscalização de ações irregulares de retirada de semente de marisco e marisco",
    finalidade: "Preservar o banco de sementes de mariscos",
    parceiros: "IAN, Colônia",
    prazo: "Curto",
    duracao: "Contínua",
    indicadores: "Número de autuações por remoção irregular de marisco no trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 26,
    responsavel: "IAN e SEAP",
    linhaAcao: "Pesca",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Aumentar a fiscalização de redes de pesca na orla",
    finalidade: "Aumentar a segurança da orla para o banho e fauna local",
    parceiros: "Colônia, Município",
    prazo: "Curto",
    duracao: "Contínua",
    indicadores: "Número de autuações ligadas à pesca no trecho",
    resultados2025: "Ampliação no período da tainha. IAN contou com 52 denúncias, 6 autuações e 16 redes apreendidas",
    status: "Em execução",
    comprovação: "Anexo 06",
    observacoes: ""
  },
  {
    n: 90,
    responsavel: "IAN e SEAP",
    linhaAcao: "Educação Ambiental",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Sensibilizar sobre as regras de pesca na orla (via colônia)",
    finalidade: "Aumentar a segurança da orla para o banho e fauna local - atingir os pescadores esporádicos",
    parceiros: "Colônia, Município",
    prazo: "Longo",
    duracao: "Contínua",
    indicadores: "Número de ações de sensibilização sobre as regras de pesca efetuadas no trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 31,
    responsavel: "IAN e SED",
    linhaAcao: "Educação Ambiental",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Buscar a implementação do projeto PROA no município",
    finalidade: "Formar protetores ambientais nas escolas",
    parceiros: "PMA",
    prazo: "Curto",
    duracao: "Pontual",
    indicadores: "Lançamento do PRAO no município / Número de ações do projeto PROA efetuadas no trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "CG/Navega deve solicitar a implementação do PROA no município à PMA/SC",
    observacoes: ""
  },
  {
    n: 33,
    responsavel: "IAN e SEIDES",
    linhaAcao: "Conservação",
    unidade: "UP2",
    trecho: "2.2. ; 2.3. ; 2.4.",
    acao: "Buscar o diálogo sobre o problema da população em vulnerabilidade social ocupando espaços protegidos no âmbito da AMFRI",
    finalidade: "Verificar experiências e possibilidades de atuação sobre a problemática regional, dado o relato de transferência de pessoas entre os municípios da AMFRI",
    parceiros: "AMFRI, OSC",
    prazo: "Médio",
    duracao: "Pontual - Contínua",
    indicadores: "Número de reuniões com a pauta da população em vulnerabilidade social da região",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 92,
    responsavel: "IAN e SEIDES",
    linhaAcao: "Cultura",
    unidade: "UP3",
    trecho: "3.1.",
    acao: "Elaborar estudo de caracterização ambiental e social da comunidade local existente (palafitas)",
    finalidade: "Manter as áreas públicas em bom estado de conservação para promover o uso do local",
    parceiros: "OSC, instituições privadas, SPU",
    prazo: "Médio",
    duracao: "Pontual - manutenção contínua",
    indicadores: "Resultado do estudo de caracterização socioambiental da área",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 58,
    responsavel: "IAN e SEINFRA",
    linhaAcao: "Acessibilidade",
    unidade: "UP2",
    trecho: "2.3.",
    acao: "Estudar a colocação das rampas no trecho - acessos sem passarela",
    finalidade: "Proporcionar maior acessibilidade no trecho; reduzir brechas nas dunas e escape de areia",
    parceiros: "Iniciativa privada",
    prazo: "Médio",
    duracao: "Pontual",
    indicadores: "Resultado do estudo de viabilidade de rampas de acesso à praia para o trecho; Número de rampas instaladas no trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 65,
    responsavel: "IAN e SEPLAN",
    linhaAcao: "Segurança",
    unidade: "UP2",
    trecho: "2.3.",
    acao: "Fomentar a celeridade na solução de embargos",
    finalidade: "Dar uso ao espaço atualmente gerando insegurança na orla",
    parceiros: "Empreendedor - Município",
    prazo: "Médio",
    duracao: "Pontual",
    indicadores: "Resultado de decisões judiciais sobre a orla do trecho",
    resultados2025: "Foi pactuado TAC com a previsão de parte da área destinada à criação de UC.",
    status: "Superada",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 46,
    responsavel: "IAN e SASAN",
    linhaAcao: "Saneamento Básico",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Elaborar e executar plano de manejo e controle de ratos",
    finalidade: "Resolver o problema de saúde pública",
    parceiros: "Instituições de ensino e pesquisa",
    prazo: "Longo",
    duracao: "Pontual - manutenção/ contínua",
    indicadores: "Lançamento do plano de manejo de ratos / Ações de manejo efetuadas",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 49,
    responsavel: "IAN, SED e SEAP",
    linhaAcao: "Segurança",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Elaborar e implementar projetos de educação para o mar",
    finalidade: "Divulgar os perigos do mar - correntes de retorno",
    parceiros: "Instituições de ensino e pesquisa, OSC, CBM, Polícia Militar Ambiental (PMA)",
    prazo: "Longo",
    duracao: "Pontual - Contínua",
    indicadores: "Lançamento do projeto de educação para o mar; Ações executadas",
    resultados2025: "Programa Golfinho CBM/SC - 362 alunos da rede municipal",
    status: "Em execução - contínua",
    comprovação: "Anexo 15",
    observacoes: ""
  },
  {
    n: 4,
    responsavel: "Resolvido",
    linhaAcao: "Fiscalização",
    unidade: "UP1",
    trecho: "1.1. ; 1.2.",
    acao: "Aumentar a fiscalização do comércio irregular de pescado (fiscal de posturas em contratação)",
    finalidade: "Retirada dos pontos de vendas não regularizados; melhoria das condições sanitárias",
    parceiros: "OSC",
    prazo: "Curto",
    duracao: "Contínua",
    indicadores: "Número de infrações por comércio irregular de pescado no trecho",
    resultados2025: "Não existe mais este problema - era na praça antes da revitalização.",
    status: "Superada",
    comprovação: "O comércio irregular de pescado era realizado na Praça Marília Soares antes da sua reforma, atividade erradicada após a revitalização do espaço público para lazer.",
    observacoes: ""
  },
  {
    n: 6,
    responsavel: "Resolvido",
    linhaAcao: "Obra Costeira",
    unidade: "UP1",
    trecho: "1.1.",
    acao: "Buscar a reutilização das rochas da autoridade portuária",
    finalidade: "Finalizar o molhe do Gravatá",
    parceiros: "Iniciativa privada",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Resultado da licitação de reutilização das rochas",
    resultados2025: "Não utilizado - mudança de estratégia",
    status: "Mudança de estratégia - finalidade: molhe executado (fase de assentamento do solo)",
    comprovação: "Anexo 02",
    observacoes: "As obras de ampliação do molhe do Rio Gravatá foram executadas com rochas de outra fonte."
  },
  {
    n: 99,
    responsavel: "Resolvido",
    linhaAcao: "Obra Costeira",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Buscar a reutilização das rochas da autoridade portuária para apoio a esportes náuticos",
    finalidade: "Dar apoio ao esporte náutico; fomentar iniciativas sociais ligadas a atividades náuticas",
    parceiros: "SPU; OSC",
    prazo: "Curto",
    duracao: "Contínua",
    indicadores: "Instrumento de autorização de uso das rochas",
    resultados2025: "Não utilizado - mudança de estratégia",
    status: "Mudança de estratégia - finalidade: molhe executado (fase de assentamento do solo)",
    comprovação: "Anexo 18",
    observacoes: "As obras de ampliação do molhe do Rio Gravatá foram executadas com rochas de outra fonte."
  },
  {
    n: 37,
    responsavel: "Secretaria de Agricultura e Pesca - SEAP",
    linhaAcao: "Fiscalização",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Comunicar a Capitania e a PMA sobre os conflitos de fiscalização (via colônia)",
    finalidade: "Esclarecer competências de fiscalização sobre embarcações artesanais",
    parceiros: "PMA, Capitania",
    prazo: "Curto",
    duracao: "Pontual",
    indicadores: "AR - Ofício sobre conflitos de fiscalização",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 15,
    responsavel: "Secretaria de Agricultura e Pesca - SEAP",
    linhaAcao: "Turismo",
    unidade: "UP1",
    trecho: "1.1. ; 1.2.",
    acao: "Fomentar a transformação de barcos de pesca artesanal para pesca esportiva",
    finalidade: "Aumentar o turismo da pesca esportiva no município",
    parceiros: "Capitania de portos; colônia de pescadores; Município",
    prazo: "Curto",
    duracao: "Sazonal",
    indicadores: "Número de barcos transformados",
    resultados2025: "Necessidade de outras ações anteriores - Criação de um GT Rio Gravatá no CG/Navega",
    status: "Previsto",
    comprovação: "Contatar EPAGRI, para buscar as parcerias como secretaria de agricultura, sebrae etc",
    observacoes: ""
  },
  {
    n: 27,
    responsavel: "SEPLAN",
    linhaAcao: "Fiscalização",
    unidade: "UP2",
    trecho: "2.1.",
    acao: "Aumentar a fiscalização do comércio irregular (fiscal de posturas em contratação)",
    finalidade: "Qualificar o atendimento do comércio na orla",
    parceiros: "Iniciativa privada",
    prazo: "Curto",
    duracao: "Sazonal",
    indicadores: "Número de autuações ligadas à orla do trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 34,
    responsavel: "SEINFRA, SEIDES e Fundação de Esportes",
    linhaAcao: "Acessibilidade",
    unidade: "UP2",
    trecho: "2.1. ; 2.4.",
    acao: "Buscar parceria com instituições de ensino para projetos de extensão com estudantes da educação física em ações de acesso de PCDs ao mar",
    finalidade: "Viabilizar o acesso dos PCD à praia com segurança.",
    parceiros: "Instituições de ensino e pesquisa",
    prazo: "Médio",
    duracao: "Pontual/ parceria - atividades/ sazonais",
    indicadores: "Parceria para projeto de extensão firmada / número de alunos atuando",
    resultados2025: "Foi utilizado para complementação de horas de alunos - Univalli",
    status: "Em execução - contínua",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 39,
    responsavel: "SEINFRA e SEIDES",
    linhaAcao: "Acessibilidade",
    unidade: "UP2",
    trecho: "2.1. ; 2.4.",
    acao: "Criar acessibilidade na faixa de praia para pessoas com mobilidade reduzida no posto 8 - esteira/EVA",
    finalidade: "Possibilitar banho de mar para pessoas que precisem de auxílio com cadeiras anfíbias.",
    parceiros: "Iniciativa privada, OSC",
    prazo: "Curto",
    duracao: "Sazonal",
    indicadores: "Número de esteiras de acesso de cadeiras anfíbias em uso no trecho",
    resultados2025: "Nas arenas de verão; no posto 8 após o engordamento",
    status: "Em execução - contínua",
    comprovação: "Anexo 10 e 11",
    observacoes: ""
  },
  {
    n: 52,
    responsavel: "SEINFRA e SEIDES",
    linhaAcao: "Acessibilidade",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Elaborar estudo para otimizar a acessibilidade na orla, com acessibilidade ao mar",
    finalidade: "Proporcionar acessibilidade à praia - livre e franco acesso ao mar",
    parceiros: "Iniciativa privada, instituições de ensino e pesquisa, OSC",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Lançamento do estudo de acessibilidade na orla",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 57,
    responsavel: "Secretaria de Infraestrutura - SEINFRA",
    linhaAcao: "Obra Costeira",
    unidade: "UP2",
    trecho: "2.1.",
    acao: "Engordamento de faixa de praia (com recuperação da restinga) do Gravatá",
    finalidade: "Retorno de atividades de turismo de sol e praia; recuperação da faixa de praia; proteção costeira frente às mudanças no clima; redução de processos erosivos; geração de emprego e renda",
    parceiros: "SPU, Capitania, IMA/IAN, BB",
    prazo: "Curto (em licenciamento)",
    duracao: "Pontual - manutenção/ contínua",
    indicadores: "Extensão e largura de praia engordada",
    resultados2025: "0 (2,4 km previsto)",
    status: "Em execução. Dados da Concorrência Eletrônica Nº 197/2025 PMN.",
    comprovação: "Anexo 17",
    observacoes: "Foram lançadas duas concorrências integrando a ampliação dos molhes do Rio Gravatá e alimentação artificial da praia, ambas fracassadas. Visando solucionar, as atividades foram separadas, com as obras do molhe em andamento e recente contratação de empresa para a execução das obras de alimentação artificial da Praia do Gravatá - Concorrência Eletrônica Nº 197/2025 PMN."
  },
  {
    n: 62,
    responsavel: "Secretaria de Infraestrutura - SEINFRA",
    linhaAcao: "Obra Costeira",
    unidade: "UP2",
    trecho: "2.1.",
    acao: "Finalizar o projeto do molhe (com a inclusão de píer) - buscar recursos/material",
    finalidade: "Otimizar a hidrodinâmica local para o acesso dos pescadores; complementar ações de manutenção do engordamento previsto",
    parceiros: "SPU, Capitania, IMA/IAN, BB",
    prazo: "Curto",
    duracao: "Pontual - manutenção/ contínua",
    indicadores: "Lançamento do projeto de conclusão do molhe do Gravatá",
    resultados2025: "Ampliação do molhe do Rio Gravatá executada.",
    status: "Superada. Molhe executado (fase de assentamento do solo - 2026)",
    comprovação: "Anexo 18",
    observacoes: "Está sendo executada a ampliação do molhe (de 70 m para 198 m), no entanto, sem píer - falta projetar e licitar o mobiliário urbano para a qualificação dos usos do molhe."
  },
  {
    n: 78,
    responsavel: "Secretaria de Infraestrutura - SEINFRA",
    linhaAcao: "Segurança",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Implementar os postos guarda-vidas previstos",
    finalidade: "Proporcionar espaço para a guarnição atuar de forma adequada",
    parceiros: "CBM, iniciativa privada",
    prazo: "Longo",
    duracao: "Pontual - manutenção/ contínua",
    indicadores: "Número de postos padrão implementados no trecho",
    resultados2025: "Em 2024 - 3 novos postos (1, 3 e 13), localizados nas praias do Pontal, Central e Meia Praia",
    status: "Superada",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 80,
    responsavel: "SEINFRA e SESEG",
    linhaAcao: "Segurança",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Instalação de câmeras de segurança na orla",
    finalidade: "Proporcionar mais segurança na orla",
    parceiros: "Polícia Militar, Iniciativa privada",
    prazo: "Longo",
    duracao: "Pontual - manutenção/ contínua",
    indicadores: "Número de câmeras operando no trecho",
    resultados2025: "Instalado sistema de Câmeras na Praça Central - T2.4. e UP3 - T3.3 - monitoramento da fila do ferry boat",
    status: "Em execução",
    comprovação: "Anexo 23",
    observacoes: ""
  },
  {
    n: 105,
    responsavel: "Secretaria de Infraestrutura - SEINFRA",
    linhaAcao: "Acessibilidade",
    unidade: "UP3",
    trecho: "3.1. ; 3.2.",
    acao: "Criar acessos que facilitem a passagem de pessoas com mobilidade reduzida",
    finalidade: "Dar acesso às pessoas com mobilidade reduzida à praia do rio Itajaí",
    parceiros: "OSC, instituições privadas, SPU",
    prazo: "Médio",
    duracao: "Pontual",
    indicadores: "Extensão de acessos acessíveis para mobilidade reduzida",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 113,
    responsavel: "Secretaria de Infraestrutura - SEINFRA",
    linhaAcao: "Obra Costeira",
    unidade: "UP3",
    trecho: "3.1.",
    acao: "Execução de revitalização do píer da orla do Itajaí",
    finalidade: "Utilizar a área para esporte e lazer",
    parceiros: "OSC, instituições privadas, autoridade portuária, SPU",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Inauguração do píer revitalizado",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 104,
    responsavel: "SEINFRA e SEAP",
    linhaAcao: "Cultura",
    unidade: "UP3",
    trecho: "3.1.",
    acao: "Implantar um deck com cais acostável para apoio à pesca artesanal e turismo (Porto do Dorico)",
    finalidade: "Garantir mais autonomia nos projetos a serem ali elaborados no Molhe",
    parceiros: "Autoridade portuária; SPU",
    prazo: "Curto",
    duracao: "Pontual",
    indicadores: "Elaboração de projeto; busca por recursos para execução",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 120,
    responsavel: "SEPLAN",
    linhaAcao: "Turismo",
    unidade: "UP3",
    trecho: "3.1.",
    acao: "Revitalização da praça da Matriz em frente ao ferryboat",
    finalidade: "Qualificar o espaço urbano no principal portão de entrada turístico",
    parceiros: "Autoridade portuária",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Dotação de recursos para revitalização da praça",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 10,
    responsavel: "SEINFRA, IAN e SETUR",
    linhaAcao: "Obra Costeira",
    unidade: "UP1",
    trecho: "1.1.",
    acao: "Elaborar projeto para a extensão do Deck contornando a foz do Gravatá (250 m)",
    finalidade: "Dar acesso à população para caminhar da praça até a ponte, com atracadouro para barcos",
    parceiros: "Iniciativa privada; IAN",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Elaboração de projeto de deck; execução da obra",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 14,
    responsavel: "SEINFRA",
    linhaAcao: "Obra Costeira",
    unidade: "UP1",
    trecho: "1.1.",
    acao: "Finalizar o projeto do molhe (com a inclusão de píer) Gravatá",
    finalidade: "Otimizar a hidrodinâmica local para o acesso dos pescadores; complementar ações de engordamento",
    parceiros: "SPU, Capitania, IMA/IAN, BB",
    prazo: "Longo",
    duracao: "Pontual - manutenção/ contínua",
    indicadores: "Lançamento do projeto de conclusão do molhe do Gravatá",
    resultados2025: "Molhe em fase de assentamento do solo - sem projeto de píer",
    status: "Em execução",
    comprovação: "Anexo 02",
    observacoes: "Está sendo executada a ampliação do molhe (de 70 m para 198 m), no entanto, sem píer - falta projetar e licitar o mobiliário urbano para a qualificação dos usos do molhe."
  },
  {
    n: 18,
    responsavel: "IAN e SEAP",
    linhaAcao: "Turismo",
    unidade: "UP1",
    trecho: "1.1. ; 1.2.",
    acao: "Identificar locais de acesso público ao rio Gravatá",
    finalidade: "Facilitação de acesso com equipamentos náuticos no rio",
    parceiros: "OSC",
    prazo: "Longo",
    duracao: "Contínua",
    indicadores: "Estudo de acesso público ao rio",
    resultados2025: "Necessidade de outras ações anteriores - Criação de um GT Rio Gravatá no CG/Navega",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 54,
    responsavel: "IAN e SEINFRA",
    linhaAcao: "Acessibilidade",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Elaborar um estudo para identificar materiais mais resistentes e mais estáveis para o deck (madeira plástica)",
    finalidade: "Melhorar a acessibilidade e reduzir a manutenção das passarelas",
    parceiros: "Instituições de ensino e pesquisa",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Resultado do estudo de materiais estáveis para estruturas da orla",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 88,
    responsavel: "PGM e IAN",
    linhaAcao: "Segurança",
    unidade: "UP2",
    trecho: "2.3.",
    acao: "Seguir normativas do Plano Diretor e PGI anterior",
    finalidade: "Dar uso ao espaço atualmente gerando insegurança na orla",
    parceiros: "Empreendedor - Município",
    prazo: "Médio",
    duracao: "Pontual",
    indicadores: "Porcentagem da área do trecho ocupada de forma regular",
    resultados2025: "Foi pactuado TAC com a previsão de parte da área destinada à criação de UC.",
    status: "Em execução",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 93,
    responsavel: "Gabinete do Prefeito",
    linhaAcao: "Cultura",
    unidade: "UP3",
    trecho: "3.1.",
    acao: "Elaborar projeto de parque linear para a área de desocupação do Itajaí",
    finalidade: "Diminuir a presença de lixo no molhe e qualificar o uso do espaço",
    parceiros: "Empresas privadas; OSC",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Lançamento de projeto de parque linear para valorização da área",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 95,
    responsavel: "Gabinete do Prefeito",
    linhaAcao: "Cultura",
    unidade: "UP3",
    trecho: "3.1.",
    acao: "Buscar a implementação do projeto da avenida gastronômica do Molhe Itajaí",
    finalidade: "Retirar os animais provindos de abandono do local; qualificar o uso turístico da área",
    parceiros: "OSC",
    prazo: "Médio",
    duracao: "Pontual",
    indicadores: "Apresentação do projeto de avenida gastronômica para a área",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 98,
    responsavel: "SEPLAN",
    linhaAcao: "Segurança",
    unidade: "UP3",
    trecho: "3.1.",
    acao: "Buscar a regularização da operação de ferryboat",
    finalidade: "Utilização do local como ponto turístico, área de lazer e contemplação",
    parceiros: "OSC, instituições privadas, autoridade portuária, SPU",
    prazo: "Longo",
    duracao: "Pontual - manutenção contínua",
    indicadores: "Emissão de devidos instrumentos autorizativos",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 103,
    responsavel: "SEPLAN",
    linhaAcao: "Segurança",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Buscar interação com a empresa privada para reformar e modernizar a estrutura atual (ferryboat)",
    finalidade: "Ter local de contemplação para turistas e moradores locais na travessia",
    parceiros: "Instituições privadas; SPU",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Ata de reunião com a ferryboat; Lançamento de projeto de revitalização",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 110,
    responsavel: "SEPLAN",
    linhaAcao: "Cultura",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Elaborar projeto de mercado público / boulevard do Itajaí",
    finalidade: "Diminuir a presença de lixo e resíduos na orla do rio Itajaí",
    parceiros: "Instituições Privadas; OSC",
    prazo: "Longo",
    duracao: "Contínuo",
    indicadores: "Lançamento de projeto de mercado público; Destinação do uso da área ao município",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 114,
    responsavel: "SEPLAN",
    linhaAcao: "Segurança",
    unidade: "UP3",
    trecho: "3.2. ; 3.3.",
    acao: "Executar projeto de desvio de rota de veículos do ferryboat",
    finalidade: "Melhorar a mobilidade urbana; reduzir congestionamentos e facilitar o uso da orla nas proximidades da prefeitura",
    parceiros: "Operadora da ferryboat",
    prazo: "Médio",
    duracao: "Pontual",
    indicadores: "Diminuição de congestionamentos no trecho",
    resultados2025: "Realizada",
    status: "Superada",
    comprovação: "Em andamento projeto de túnel. Monitoramento ao vivo online da fila do ferry boat.",
    observacoes: ""
  },
  {
    n: 36,
    responsavel: "SEPLAN e SESEG",
    linhaAcao: "Segurança",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Compatibilizar faixa de pedestres e passarelas/acessos da orla",
    finalidade: "Otimizar a chegada do pedestre à praia, reduzir a criação de trilhas na restinga",
    parceiros: "Município",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Número de faixas compatibilizadas no trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 61,
    responsavel: "SEPLAN e SESEG",
    linhaAcao: "Segurança",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Estudar/Implementar bolsões para paradas dos ônibus coletivos na orla",
    finalidade: "Otimizar o trânsito, proporcionar o acesso dos cidadãos à orla",
    parceiros: "Município",
    prazo: "Médio",
    duracao: "Pontual",
    indicadores: "Número de bolsões de ônibus coletivos implementados",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 112,
    responsavel: "SEPLAN e SEAP",
    linhaAcao: "Pesca",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Elaborar projeto do Porto Dorico (portinho) localizado entre as palafitas",
    finalidade: "Espaço de livre acesso ao público local e turístico na beira-rio",
    parceiros: "Instituição privada; SPU; capitania dos portos",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Lançamento de projeto de Porto Dorico; Destinação da área ao município",
    resultados2025: "Em discussão.",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 50,
    responsavel: "SEPLAN e SPCA",
    linhaAcao: "Turismo",
    unidade: "UP2",
    trecho: "2.2. ; 2.3. ; 2.4.",
    acao: "Elaborar estudo para a criação de espaço 'dogs beach' na orla",
    finalidade: "Buscar uma alternativa segura para os animais de estimação na praia",
    parceiros: "Iniciativa privada, instituições de ensino e pesquisa, OSC",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Lançamento do estudo de dogs beach",
    resultados2025: "Está sendo dialogado um trecho na Meia Praia - via SEPLAN e Bem-estar Animal - verificar legislação e recomendações do CRMV.",
    status: "Mudança de estratégia - em execução - solicitada a remoção da ação",
    comprovação: "O CG/Navega não tem interesse na ação, pois tem petplace nas praças e não é permitido pelo código de posturas devido aos riscos à saúde do animal, dos humanos e da vida silvestre.",
    observacoes: ""
  },
  {
    n: 59,
    responsavel: "SEPLAN, SASAN e IAN",
    linhaAcao: "Turismo",
    unidade: "UP2",
    trecho: "2.2.",
    acao: "Estudar a criação de um píer turístico e com pesca esportiva, junto com o 'emissário'",
    finalidade: "Atrair mais turistas para a foz do Ribeirão das Pedras",
    parceiros: "SPU",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Lançamento do projeto de uso sustentável e integrado da orla",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: "Relação com a manutenção do tempo de vida do engordamento de praia e possibilidade de assoreamento da foz do ribeirão."
  },
  {
    n: 28,
    responsavel: "Secretaria de Proteção e Cuidado Animal - SPCA",
    linhaAcao: "Fiscalização",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Aumentar iniciativas de fiscalização de animais domésticos na faixa de praia",
    finalidade: "Coibir o passeio irregular de cães na faixa de praia",
    parceiros: "Município",
    prazo: "Curto",
    duracao: "Contínua",
    indicadores: "Número de abordagens de fiscalização efetuadas",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "Riscos à saúde do animal, dos humanos e da vida silvestre.",
    observacoes: ""
  },
  {
    n: 72,
    responsavel: "Secretaria de Proteção e Cuidado Animal - SPCA",
    linhaAcao: "Educação Ambiental",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Fomentar projetos de sensibilização sobre proibição de cães na praia",
    finalidade: "Divulgar os riscos para o cão, para o ambiente e para os usuários da orla",
    parceiros: "Iniciativa privada, instituições de ensino e pesquisa, OSC",
    prazo: "Curto",
    duracao: "Contínua",
    indicadores: "Número de projetos de sensibilização sobre a problemática efetuados no trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "Riscos à saúde do animal, dos humanos e da vida silvestre.",
    observacoes: ""
  },
  {
    n: 100,
    responsavel: "Secretaria de Proteção e Cuidado Animal - SPCA",
    linhaAcao: "Saneamento Básico",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Buscar a transferência dos animais abandonados no molhe para o bem-estar animal",
    finalidade: "Dar apoio a atividades náuticas e qualificar a orla do rio",
    parceiros: "Instituições privadas, SPU, capitania dos portos",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Número de animais abandonados no molhe",
    resultados2025: "Realizada",
    status: "Superada",
    comprovação: "Riscos à saúde do animal, dos humanos e da vida silvestre.",
    observacoes: "Anexo 31"
  },
  {
    n: 43,
    responsavel: "SETUR, SED e Legislativo",
    linhaAcao: "Conservação",
    unidade: "UP2",
    trecho: "2.1.",
    acao: "Criar uma Lei Municipal de Cultura Oceânica",
    finalidade: "Incluir a cultura oceânica nas escolas de Navegantes",
    parceiros: "IAN, Colônia, OSC, instituições de ensino e pesquisa",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Número de encontros para discussão / Lançamento da lei municipal",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "Anexo 12",
    observacoes: "Em nível estadual foi sancionada a Lei 19.247/2025 - Dia Estadual da Promoção da Cultura Oceânica. Destaca-se o Clube de Cultura Oceânica da Escola Municipal Professora Maria Ivone Müller dos Santos, pioneiro em Santa Catarina no programa Escola Azul Brasil."
  },
  {
    n: 79,
    responsavel: "Secretaria de Turismo - SETUR",
    linhaAcao: "Turismo",
    unidade: "UP2",
    trecho: "2.1.",
    acao: "Incentivar a aplicação da legislação que já prevê o atendimento dos restaurantes da orla na faixa de praia",
    finalidade: "Viabilizar o uso comercial da praia e gerar receitas (depende do engordamento)",
    parceiros: "Iniciativa privada",
    prazo: "Longo",
    duracao: "Contínua",
    indicadores: "Número de restaurantes atendendo na orla do trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 115,
    responsavel: "Secretaria de Turismo - SETUR",
    linhaAcao: "Turismo",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Fomentar projetos que atraiam turistas para o molhe do Itajaí",
    finalidade: "Qualificar o serviço e receptivo turístico dos usuários do ferryboat",
    parceiros: "Ferryboat, Município, SPU, capitania dos portos",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Número de eventos e projetos turísticos realizados no trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 42,
    responsavel: "Secretaria de Turismo - SETUR",
    linhaAcao: "Turismo",
    unidade: "UP2",
    trecho: "2.4.",
    acao: "Criar totem com horários de melhor avistagem de aviões (Mirante)",
    finalidade: "Fomentar atrações turísticas locais e aproximar do aeroporto",
    parceiros: "Aeroporto",
    prazo: "Curto",
    duracao: "Pontual - manutenção contínua",
    indicadores: "Totem instalado junto ao mirante dos aviões",
    resultados2025: "Projeto de Toten com horários elaborado - instalação prevista em breve",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 81,
    responsavel: "SETUR e Fundação de Esportes",
    linhaAcao: "Turismo",
    unidade: "UP2",
    trecho: "2.4.",
    acao: "Manter e fortalecer campeonatos de surf em Navegantes",
    finalidade: "Geração de emprego, renda (hospedagem, alimentação) e reconhecimento do município na prática",
    parceiros: "Iniciativa privada, OSC",
    prazo: "Curto",
    duracao: "Contínua",
    indicadores: "Número de campeonatos de surf efetuados no trecho",
    resultados2025: "4 eventos realizados",
    status: "Em execução - contínua",
    comprovação: "Anexo 24",
    observacoes: "Foram realizados dois Circuitos relevantes nas praias de Navegantes em 2025: em setembro o CBSurf Navegantes Festival, na Praia Central (T2.4.); e o Circuito Navegantes de Surf, com a 1ª etapa em julho, e 3ª em setembro, na Praia Central, e a 2ª etapa na Praia do Gravatá (T2.1) em agosto."
  },
  {
    n: 84,
    responsavel: "SETUR e Fundação de Esportes",
    linhaAcao: "Turismo",
    unidade: "UP2",
    trecho: "2.2. ; 2.3. ; 2.4.",
    acao: "Manter e fortalecer os eventos de pesca esportiva",
    finalidade: "Geração de emprego e renda, reconhecimento nacional do município na pesca",
    parceiros: "Iniciativa privada, OSC",
    prazo: "Curto",
    duracao: "Contínua",
    indicadores: "Número de eventos de pesca esportiva efetuados",
    resultados2025: "3 eventos realizados",
    status: "Em execução - contínua",
    comprovação: "Anexo 25",
    observacoes: "Em 2025 foi realizado o 4º Festival de Pesca, na UP2 T2.4, compondo a programação de aniversário de Navegantes, reunindo 230 pescadores."
  },
  {
    n: 24,
    responsavel: "SETUR e Fundação de Esportes",
    linhaAcao: "Turismo",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Ampliação de quadras multiesportivas na areia",
    finalidade: "Proporcionar lazer, segurança e incentivo ao esporte",
    parceiros: "Iniciativa privada, OSC",
    prazo: "Médio",
    duracao: "Pontual - manutenção/ contínua",
    indicadores: "Número de quadras esportivas na praia do trecho",
    resultados2025: "Inviabilidade ambiental - as praias de Navegantes são muito estreitas e não há espaço para quadras esportivas na faixa de areia na maré alta",
    status: "Mudança de estratégia - Praia do Pontal - restinga herbácea",
    comprovação: "Anexo 05",
    observacoes: "Navegantes deve sediar a Etapa Nacional e Internacional de Vôlei de Praia, para isso, foi solicitada autorização do órgão ambiental para a instalação de infraestruturas em faixa de restinga herbácea recente da Praia do Pontal, com manutenção de dunas frontais. Em fase de complementação de estudos."
  },
  {
    n: 44,
    responsavel: "SETUR e Gabinete do Prefeito",
    linhaAcao: "Turismo",
    unidade: "UP2",
    trecho: "2.4.",
    acao: "Demonstrar o interesse do município em absorver a área portuária para uso público",
    finalidade: "Viabilizar a instalação de infraestruturas fixas de turismo e lazer",
    parceiros: "Autoridade Portuária - SPU",
    prazo: "Curto",
    duracao: "Pontual",
    indicadores: "Reunião de formalização de intenções efetuadas",
    resultados2025: "Inclusão da área almejada no âmbito da poligonal do Mapa do TAGP.",
    status: "Mudança de estratégia - em execução - Mapa do TAGP em análise SPU/UC.",
    comprovação: "Anexo 13 e 14",
    observacoes: "A área está sendo integrada ao polígono do TAGP. Peça técnica em elaboração, com discussão prévia sobre a área em questão em reunião com a SPU, previamente aprovada devido à compatibilidade com as características de orla e uso público de Terreno de Marinha."
  },
  {
    n: 106,
    responsavel: "SETUR e Gabinete do Prefeito",
    linhaAcao: "Turismo",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Demonstrar o interesse do município em absorver essa área para uso público turístico",
    finalidade: "Tornar o local um atrativo turístico de beira-rio mais receptivo perto da balsa",
    parceiros: "Operadora do Ferry; SPU",
    prazo: "Longo",
    duracao: "Sazonal",
    indicadores: "Reunião de formalização de intenções efetuadas",
    resultados2025: "Inclusão da área almejada no âmbito da poligonal do Mapa do TAGP.",
    status: "Mudança de estratégia - em execução - Mapa do TAGP em análise SPU/UC.",
    comprovação: "Anexo 13 e 14",
    observacoes: "A área está sendo integrada ao polígono do TAGP. Peça técnica em elaboração, com discussão prévia sobre a área em questão em reunião com a SPU, previamente aprovada devido à compatibilidade com as características de orla e uso público de Terreno de Marinha."
  },
  {
    n: 119,
    responsavel: "SETUR e Gabinete do Prefeito",
    linhaAcao: "Turismo",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Manter as tratativas atuais de uso da área concedida à autoridade portuária para acervo histórico",
    finalidade: "Dotar o município de um espaço de resgate da história da travessia e da pesca",
    parceiros: "Instituições público/privadas; OSC; comunidade pesqueira",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Formalização da parceria de uso da área",
    resultados2025: "Inclusão da área almejada no âmbito da poligonal do Mapa do TAGP.",
    status: "Mudança de estratégia - em execução - Mapa do TAGP em análise SPU/UC.",
    comprovação: "Anexo 13 e 14",
    observacoes: "Com os estudos para a elaboração do polígono do TAGP foi verificado que a área não está na poligonal do porto organizado, sendo viável sua integração ao polígono do TAGP. No entanto, mantém-se a comunicação com a autoridade portuária dada a interpretação anterior."
  },
  {
    n: 107,
    responsavel: "SETUR e SEAP",
    linhaAcao: "Turismo",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Elaborar e implementar projeto para que embarcações pesqueiras possibilitem a presença de turistas",
    finalidade: "Fomentar o turismo na orla do Rio Itajaí e qualificar o cenário do rio",
    parceiros: "SPU",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Projeto de regularização de embarcações para turismo; Número de barcos transformados",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 101,
    responsavel: "SETUR e SEAP",
    linhaAcao: "Pesca",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Buscar apoio de projetos para transformar parte da frota de pesca artesanal para pesca esportiva",
    finalidade: "Qualificar o uso da área com potencial turístico da foz do Itajaí",
    parceiros: "Instituições privadas; OSC, SPU",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Projeto de regularização de embarcações para turismo; Número de barcos transformados",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 45,
    responsavel: "SETUR e SEPLAN",
    linhaAcao: "Turismo",
    unidade: "UP2",
    trecho: "2.1.",
    acao: "Elaboração e implementação de projeto de píer junto ao molhe do Gravatá",
    finalidade: "Proporcionar áreas de lazer, exploração econômica, e ampliar o uso por atividades da orla (pesca, contemplação)",
    parceiros: "Iniciativa privada, instituições de ensino e pesquisa, OSC",
    prazo: "Médio",
    duracao: "Pontual - manutenção/ contínua",
    indicadores: "Lançamento do projeto de píer junto ao molhe do Gravatá",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: "Está sendo executada a ampliação do molhe (de 70 m para 198 m), no entanto, sem píer - falta projetar e licitar o mobiliário urbano para a qualificação dos usos do molhe."
  },
  {
    n: 55,
    responsavel: "SETUR e SEPLAN",
    linhaAcao: "Turismo",
    unidade: "UP2",
    trecho: "2.1.",
    acao: "Elaborar um projeto complementar para a requalificação da orla, integração da orla do Gravatá",
    finalidade: "Proporcionar o uso e o lazer na orla, com acessibilidade universal ao mar",
    parceiros: "SPU, IAN/IMA, MTur",
    prazo: "Médio",
    duracao: "Pontual - manutenção/ contínua",
    indicadores: "Lançamento de projeto complementar de requalificação da orla do Gravatá",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: "Relação com engordamento de faixa de praia"
  },
  {
    n: 75,
    responsavel: "SETUR e SEPLAN",
    linhaAcao: "Turismo",
    unidade: "UP2",
    trecho: "2.1.",
    acao: "Implementar incentivos para atividades de comércio turístico no térreo dos prédios / fachada ativa",
    finalidade: "Trazer 'vida' à orla de Navegantes seguindo as previsões do Plano Diretor",
    parceiros: "Iniciativa Privada",
    prazo: "Curto",
    duracao: "Pontual",
    indicadores: "Número de comércios turísticos nos térreos da orla do trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 94,
    responsavel: "SETUR e SEPLAN",
    linhaAcao: "Turismo",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Elaborar projeto de utilização do molhe Itajaí para fins recreativos e buscar autorização/parceria",
    finalidade: "Área de apoio à pesca artesanal; espaço turístico qualificado",
    parceiros: "SPU; capitania dos portos; colônia de pesca",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Lançamento do projeto de qualificação do molhe",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 96,
    responsavel: "SETUR e SEPLAN",
    linhaAcao: "Turismo",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Executar o projeto do parque linear (1) sobre o molhe",
    finalidade: "Aproveitamento do atual prédio da prefeitura se for desocupado ou da atual quadra e pista de skate.",
    parceiros: "SPU",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Porcentagem de conclusão das infraestruturas previstas no projeto",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 121,
    responsavel: "SETUR e SEPLAN",
    linhaAcao: "Turismo",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Revitalizar as áreas públicas próximas ao molhe Itajaí",
    finalidade: "Dar nova opção de renda/emprego para o pescador artesanal local",
    parceiros: "SPU; capitania dos portos; colônia de pesca",
    prazo: "Longo",
    duracao: "Sazonal",
    indicadores: "Número de espaços públicos revitalizados no trecho",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 111,
    responsavel: "SETUR e SEPLAN",
    linhaAcao: "Turismo",
    unidade: "UP3",
    trecho: "3.1.",
    acao: "Elaborar projeto de Píer motoaquático anexo ao prédio da atual prefeitura",
    finalidade: "Buscar regularizar o pescador para que possa promover, além de pesca, o turismo embarcado",
    parceiros: "Colônia de pescadores; capitania dos portos",
    prazo: "Médio",
    duracao: "Sazonal",
    indicadores: "Lançamento de projeto do píer anexo à prefeitura",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 117,
    responsavel: "SETUR e SEPLAN",
    linhaAcao: "Turismo",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Implementar o parque linear próximo à atual prefeitura e ferryboat",
    finalidade: "Regularização fundiária e ambiental da orla do Itajaí",
    parceiros: "SPU, Defesa civil",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Destinação do uso da área ao município; Extensão da implementação de projeto de parque linear",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 122,
    responsavel: "SETUR e SEPLAN",
    linhaAcao: "Turismo",
    unidade: "UP3",
    trecho: "3.1.",
    acao: "Revitalizar Praça de contemplação da comunidade ao lado da prefeitura de Navegantes",
    finalidade: "Uso constante da área visando trazer segurança para o local",
    parceiros: "OSC, instituições privadas; colônia de pescadores",
    prazo: "Médio",
    duracao: "Contínuo",
    indicadores: "Lançamento do projeto de revitalização; Porcentagem de conclusão",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 108,
    responsavel: "SETUR e SEPLAN",
    linhaAcao: "Turismo",
    unidade: "UP3",
    trecho: "3.2.",
    acao: "Elaborar estudo para uso de área no molhe para esporte náutico",
    finalidade: "Qualificação e ativação esportiva do molhe Itajaí",
    parceiros: "Instituições privadas; operadora do ferry; SPU",
    prazo: "Longo",
    duracao: "Pontual",
    indicadores: "Lançamento do estudo para uso náutico no molhe",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: ""
  },
  {
    n: 30,
    responsavel: "SETUR e SESEG",
    linhaAcao: "Segurança",
    unidade: "UP2",
    trecho: "2.1. ; 2.2. ; 2.3. ; 2.4.",
    acao: "Buscar a atuação dos guarda-vidas o ano todo nas praias municipais",
    finalidade: "Melhorar a segurança dos banhistas e reduzir o vandalismo na orla",
    parceiros: "CBM",
    prazo: "Médio",
    duracao: "Pontual - contínua",
    indicadores: "Número de guarda-vidas atuando em baixa temporada",
    resultados2025: "Quatro: Posto 2 – Centro, na praça central; Posto 8 – Meia Praia; Posto 16 – Gravatá; Posto 19 – Gravatá.",
    status: "Em execução",
    comprovação: "-",
    observacoes: "Ampliar atuações em finais de semana e feriados fora de temporada."
  },
  {
    n: 85,
    responsavel: "SETUR e SASAN",
    linhaAcao: "Saneamento Básico",
    unidade: "UP2",
    trecho: "2.4.",
    acao: "Monitorar a balneabilidade da área e buscar a certificação Bandeira Azul",
    finalidade: "Qualificar o turismo local, atendendo a rígidos critérios ecológicos e sanitários internacionais",
    parceiros: "Iniciativa privada, instituições de ensino e pesquisa, OSC, IMA",
    prazo: "Médio",
    duracao: "Contínua",
    indicadores: "Quantidade de monitoramento da qualidade da água efetuados",
    resultados2025: "Programa de Balneabilidade SEMAE - em andamento. Bandeira Azul - sem andamento.",
    status: "Em execução - contínua. Solicitar fase piloto Bandeira Azul (verificar trecho)",
    comprovação: "Anexo 26",
    observacoes: "A orla do trecho é contemplada com o Programa Estadual de Balneabilidade (Ponto 05), no entanto, para a premiação Bandeira Azul, essas análises precisam ser complementadas, o que ainda não foi providenciado."
  },
  {
    n: 20,
    responsavel: "SETUR, IAN e SEPLAN",
    linhaAcao: "Educação Ambiental",
    unidade: "UP1",
    trecho: "1.1. ; 1.2.",
    acao: "Implementar projetos de Educação e ecoturismo no Gravatá",
    finalidade: "Fomentar o turismo ecológico voltado à educação ambiental; visar melhor qualidade de proteção ao manguezal",
    parceiros: "OSC; instituição de ensino e pesquisa",
    prazo: "Longo",
    duracao: "Contínua",
    indicadores: "Número de projetos de educação e ecoturismo implementados",
    resultados2025: "Sob análise junto à pasta",
    status: "Previsto",
    comprovação: "-",
    observacoes: "Trabalho interdisciplinar (com outras secretarias) - cicloturismo e turismo rural - solicitar apoio EPAGRI para reunir parcerias."
  }
];
